codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "45...100"
  
  status:
    project:
      default:
        target: 45%
        threshold: 1%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        target: 25%
        threshold: 2%

ignore:
  - "cmd/*/main.go"
  - "scripts/"
  - "test/"
  - "**/*_test.go"
  - ".cursor/"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

github_checks:
  annotations: true 